name: Build Packages
# Build Source and Wheel Packages

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      need_wheel:
        default: true
        required: false
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  build_wheel:
    name: 🚀 CIBW (${{matrix.buildplat[0]}}_${{matrix.python}})
    needs: build_sdist
    if: ${{ inputs.need_wheel }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - [ubuntu-20.04, manylinux_x86_64]
          - [macos-11, macosx_x86_64]
          # - [macos-12, macosx_x86_64]
          # - [windows-2019, win_amd64]
          - [windows-2022, win_amd64]
        python:
          - 'cp310'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Set up Python3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Build wheel with CIBW
        uses: pypa/cibuildwheel@v2.6.0
        env:
          CIBW_BEFORE_BUILD: >-
            pip install versioningit &&
            python .github/scripts/tweak_tag_in_cibw.py
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          CIBW_TEST_REQUIRES: pytest pytest-cov
          CIBW_TEST_COMMAND: pytest -v --no-cov {package}/tests

      - name: Upload wheel as Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: >-
            wheel_${{ startsWith(matrix.buildplat[0], 'ubuntu') && 'linux' ||
              (
                startsWith(matrix.buildplat[0], 'macos') && 'macos' || 'windows'
              )
            }}
          path: wheelhouse/*.whl
          retention-days: 3

  collect_wheels:
    name: 🫘 collect wheels
    needs: build_wheel
    if: ${{ inputs.need_wheel }}
    runs-on: ubuntu-latest
    steps:
      - name: Download linux wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel_linux
          path: wheelhouse

      - name: Download macos wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel_macos
          path: wheelhouse

      - name: Download windows wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel_windows
          path: wheelhouse

      - name: Upload collected wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/*.whl
          retention-days: 3

      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            wheel_macos
            wheel_linux
            wheel_windows
          failOnError: false

  build_sdist:
    name: 📦 build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install versioningit
          python -m pip install build

      - name: Build sdist Package with Extension
        run: |
          python .github/scripts/tweak_tag_in_cibw.py
          python -m build -s

      - name: Upload sdist as Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 3
