name: Wheels building

on:
  push:
  pull_request:
  issue_comment:
    types: created
  release:
    types: released
  schedule:
    - cron: "30 1 * * 4"
  workflow_dispatch:

jobs:
  build_package:
    uses: ./.github/workflows/build.yml
    if: >-
      contains(github.event.head_commit.message, '[wheel build]') ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'release' ||
      (github.event_name == 'pull_request' && contains(github.event.action, 'opened')) ||
      (github.event.issue.pull_request && github.event.comment.body == '/build')
    with:
      ref: >-
        ${{ github.event.pull_request &&
          github.event.pull_request.head.ref || github.ref_name
        }}
      need_wheel: true
      need_sdist: true

  run_tests:
    needs: build_package
    uses: ./.github/workflows/test.yml
    with:
      ref: >-
        ${{ github.event.pull_request &&
          github.event.pull_request.head.ref || github.ref_name
        }}
      os: Linux
      python_version: "3.10"
    secrets: inherit

  update_PR_Comment:
    needs: run_tests
    if: ${{ github.event.pull_request || github.event.issue.pull_request }}
    uses: ./.github/workflows/comment.yml

  pypa_publish:
    needs: [build_package, run_tests]
    uses: ./.github/workflows/publish_pypi.yml
    if: needs.run_tests.outputs.test_passed
    with:
      ref: >-
        ${{ github.event.pull_request &&
          github.event.pull_request.head.ref || github.ref_name
        }}
      is_release: ${{ github.event_name == 'release' }}
      rev: ${{ needs.build_package.outputs.rev }}
      next_rev: ${{ needs.build_package.outputs.next_rev }}
    secrets: inherit
