name: Wheels building

on:
  push:
  pull_request:
  issue_comment:
    types: created
  release:
    types: released
  schedule:
    - cron: "30 1 * * 4"
  workflow_dispatch:

jobs:
  build_package:
    uses: ./.github/workflows/build.yml
    if: >-
      contains(github.event.head_commit.message, '[wheel build]') ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'release' ||
      (github.event_name == 'pull_request' && contains(github.event.action, 'opened')) ||
      (github.event.issue.pull_request && github.event.comment.body == '/build')
    with:
      ref: >-
        ${{ github.event.pull_request &&
          github.event.pull_request.head.ref || github.ref_name
        }}
      need_wheel: true
      need_sdist: true

  run_tests:
    needs: build_package
    uses: ./.github/workflows/test.yml
    with:
      ref: >-
        ${{ github.event.pull_request &&
          github.event.pull_request.head.ref || github.ref_name
        }}
      os: Linux
      python_version: "3.10"
    secrets: inherit

  update_PR_Comment:
    needs: run_tests
    if: ${{ github.event.pull_request || github.event.issue.pull_request }}
    uses: ./.github/workflows/comment.yml

  pypa_publish:
    name: ✨ publish to PYPY
    needs: [build_package, run_tests]
    runs-on: ubuntu-latest
    if: >-
      needs.run_tests.outputs.test_passed
    steps:
      - name: Download sdist
        uses: actions/download-artifact@v3
        with:
          name: sdist
          path: dist

      - name: Download all wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - name: Publish package to TestPyPI
        if: github.event_name != 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
          print_hash: true

      - name: Publish package to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
          print_hash: true
